# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yurdosii or simplier Yurka
email: south_farsh@ukr.net
description: > # this means to ignore newlines until "baseurl:"
 I HAVE MADE THIS SITE ALMOST BY MYSELF.OOO what to say? i dont know i can say that i have just finished school and have passed final exams.
You can edit this  line in _config.yml. 
It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Yurdos_sii
github_username:  Yurdos

# Build settings
markdown: kramdown
